<?php acf_add_local_field_group(array(
	'key' => 'group_5e98967d44cc1',
	'title' => 'Footer Settings',
	'fields' => array(
		array(
			'key' => 'field_5e9dcdc7dadb3',
			'label' => 'Contact Info',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e9dcdbcdadb2',
			'label' => 'Footer Logo (Optional)',
			'name' => 'footer_logo',
			'type' => 'image',
			'instructions' => 'Select a logo to display in the footer. If a logo is not selected, the site\'s name will be shown instead.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ea06b34321fe',
			'label' => 'Footer Button (Optional)',
			'name' => 'footer_button',
			'type' => 'link',
			'instructions' => '"Link Text" will be shown in this button below site branding in the footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5eb1b57b46bad',
			'label' => 'Address Format (Optional)',
			'name' => 'address_format',
			'type' => 'textarea',
			'instructions' => 'Please enter how you\'d like your address to be displayed here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 2,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5e98975c758bf',
			'label' => 'Engagement',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fda2c45bdcdf',
			'label' => 'Title',
			'name' => 'engagement_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd920ee00b8d',
			'label' => 'Content',
			'name' => 'has_instagram',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Instagram',
			'ui_off_text' => 'Quick Links',
		),
		array(
			'key' => 'field_5e98a4b7ffaa5',
			'label' => 'Quick Links',
			'name' => 'quick_links',
			'type' => 'repeater',
			'instructions' => 'Set links for the Quick Links section in the footer. *Max: 8',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fd920ee00b8d',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 8,
			'layout' => 'block',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_5e98a503ffaa7',
					'label' => 'Link',
					'name' => 'quick_link',
					'type' => 'link',
					'instructions' => '"Link Text" will be in this link.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-footer-settings',
			),
		),
	),
	'menu_order' => 98,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set values for the site\'s footer.',
));
