<?php acf_add_local_field_group(array(
	'key' => 'group_5e98af665ed63',
	'title' => 'Hero',
	'fields' => array(
		array(
			'key' => 'field_5e98af666596c',
			'label' => 'Hero Type',
			'name' => 'hero_is_video',
			'type' => 'true_false',
			'instructions' => 'Is the hero section a video or an image slider?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Video',
			'ui_off_text' => 'Image',
		),
		array(
			'key' => 'field_5e98af666cbc7',
			'label' => 'Hero Overlay',
			'name' => 'hero_overlay',
			'type' => 'select',
			'instructions' => 'Select the level of overlay for the hero section.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'0' => 'No Overlay',
				'0.125' => 'Extra Light Overlay',
				'0.25' => 'Light Overlay',
				'0.5' => 'Medium Overlay',
				'0.75' => 'Heavy Overlay',
			),
			'default_value' => array(
				0 => '0.25',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e98af6665a50',
			'label' => 'Hero Video',
			'name' => 'hero_video',
			'type' => 'group',
			'instructions' => 'Set the values for the hero video here.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e98af666596c',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e9f0909e9304',
					'label' => 'mp4',
					'name' => 'mp4',
					'type' => 'file',
					'instructions' => 'Add a video file here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => 12,
					'mime_types' => 'mp4, webm, ogg',
				),
				array(
					'key' => 'field_5e9f0a5ae9305',
					'label' => 'webm',
					'name' => 'webm',
					'type' => 'file',
					'instructions' => 'Add a video file here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => 12,
					'mime_types' => 'webm',
				),
				array(
					'key' => 'field_5e9f0ab9e9306',
					'label' => 'Loading Image (Optional)',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'This image will be shown until the video is loaded.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5e9f3d312c788',
					'label' => 'Title (Optional)',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'This text will be displayed prominently over the hero video. *Max: 50 characters',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 50,
				),
				array(
					'key' => 'field_5e9f3d392c789',
					'label' => 'Text (Optional)',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'This text will be displayed over the hero video (less prominent than the title). *Max: 60 characters',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 65,
				),
				array(
					'key' => 'field_5e9f3d542c78a',
					'label' => 'Button (Optional)',
					'name' => 'button',
					'type' => 'link',
					'instructions' => 'This button will be rendered over the hero video, with "Link Text" shown in it.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5e98af666267b',
			'label' => 'Hero Slides',
			'name' => 'hero_slides',
			'type' => 'repeater',
			'instructions' => 'Set the values for the hero slider here. *Min: 1, Max: 4',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5e98af666596c',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 4,
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array(
				array(
					'key' => 'field_5e98af66659a7',
					'label' => 'Slide Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Select the image for this slide\'s background.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e98af666596c',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'large',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5e98af66659df',
					'label' => 'Slide Title (Optional)',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'This text will be displayed prominently over this slide. *Max: 50 characters',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e98af666596c',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 50,
				),
				array(
					'key' => 'field_5e9f3d7d2c78b',
					'label' => 'Slide Text (Optional)',
					'name' => 'text',
					'type' => 'text',
					'instructions' => 'This text will be displayed over this slide (less prominent than the title). *Max: 60 characters',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 60,
				),
				array(
					'key' => 'field_5e98af6665a17',
					'label' => 'Slide Button (Optional)',
					'name' => 'button',
					'type' => 'link',
					'instructions' => 'This button will be rendered over this slide, with "Link Text" shown in it.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e98af666596c',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'homepage.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set the values for the hero section (just below the header at the top of the homepage).',
));
