<?php acf_add_local_field_group(array(
	'key' => 'group_5e98cbac5f3b6',
	'title' => 'Masses',
	'fields' => array(
		array(
			'key' => 'field_5e98cbac62d31',
			'label' => 'Title',
			'name' => 'masses_title',
			'type' => 'text',
			'instructions' => 'This title will be shown at the top of the mass times section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e98cbac62d64',
			'label' => 'Subtitle',
			'name' => 'masses_subtitle',
			'type' => 'text',
			'instructions' => 'This subtitle will be shown at the top of the mass times section, under the title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e99eaf5f52dd',
			'label' => 'Mass Times',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Mass Times are set in <a href="/wp-admin/admin.php?page=theme-general-settings" title="Theme Settings">Theme Settings &gt; Theme Settings</a>.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5e98d76b34986',
			'label' => 'Buttons (Optional)',
			'name' => 'masses_buttons',
			'type' => 'repeater',
			'instructions' => 'Add up to 2 buttons that can be displayed at the bottom of the mass times section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 2,
			'layout' => 'block',
			'button_label' => 'Add Button',
			'sub_fields' => array(
				array(
					'key' => 'field_5e98d7b734987',
					'label' => 'Button',
					'name' => 'button',
					'type' => 'link',
					'instructions' => '"Link Text" will be shown in this button.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'homepage.php',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set the values for the mass times section on the homepage.',
));
