<?php acf_add_local_field_group(array(
	'key' => 'group_5e98b7ca14041',
	'title' => 'News',
	'fields' => array(
		array(
			'key' => 'field_5e98bd905507a',
			'label' => 'Title',
			'name' => 'news_title',
			'type' => 'text',
			'instructions' => 'This title will be shown at the top of the news section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e98c32a3d0b4',
			'label' => 'Subtitle',
			'name' => 'news_subtitle',
			'type' => 'text',
			'instructions' => 'This subtitle will be shown at the top of the news section, below the title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e98b7cea6270',
			'label' => 'Category',
			'name' => 'news_category',
			'type' => 'taxonomy',
			'instructions' => 'Select a category of posts to display in the news section.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5e98bda65507b',
			'label' => 'Link (Optional)',
			'name' => 'news_link',
			'type' => 'link',
			'instructions' => '"Link Text" will be shown in the link above the news posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'homepage.php',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set the values for the news section on the homepage.',
));
