<?php acf_add_local_field_group(array(
	'key' => 'group_5eea423710e17',
	'title' => 'Staff',
	'fields' => array(
		array(
			'key' => 'field_5eea42eca8233',
			'label' => 'Position',
			'name' => 'position',
			'type' => 'text',
			'instructions' => 'Staff member’s job title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
    array(
			'key' => 'field_5eebcb9bcfdbc',
			'label' => 'Has Link?',
			'name' => 'has_link',
			'type' => 'true_false',
			'instructions' => 'Leave this unchecked unless you have a custom contact link.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Link',
			'ui_off_text' => 'Email',
		),
		array(
			'key' => 'field_5eea4305a8234',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => 'Staff member’s email address',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5eebcb9bcfdbc',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '<i class="fa fa-envelope"></i>',
			'append' => '',
		),
    array(
			'key' => 'field_5eebcbe3cfdbd',
			'label' => 'Link',
			'name' => 'link',
			'type' => 'link',
			'instructions' => 'Custom link to contact staff member',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5eebcb9bcfdbc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5eea43c4a8235',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => 'Staff member’s phone number',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '<i class="fa fa-phone"></i>',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'staff',
			),
		),
	),
	'menu_order' => 90,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Information for the Staff Custom Post Type',
));
