<?php acf_add_local_field_group(array(
	'key' => 'group_5dcf08b97b22f',
	'title' => 'Custom Settings',
	'fields' => array(
		array(
			'key' => 'field_5dd2aca1b28a8',
			'label' => 'Theme Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5dcf08c885042',
			'label' => 'Primary Color',
			'name' => 'primary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2C213A',
		),
		array(
			'key' => 'field_5dcf08d985043',
			'label' => 'Secondary Color',
			'name' => 'secondary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#832928',
		),
		array(
			'key' => 'field_5dcf08e285044',
			'label' => 'Tertiary Color',
			'name' => 'tertiary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#C0973C',
		),
		array(
			'key' => 'field_5dcf08f285045',
			'label' => 'Quaternary Color',
			'name' => 'quaternary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#395F95',
		),
		array(
			'key' => 'field_5ebc5847eb976',
			'label' => 'Fonts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ebc89d7ddfdd',
			'label' => 'Imports',
			'name' => 'font_imports',
			'type' => 'repeater',
			'instructions' => 'Add hosted fonts',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Import',
			'sub_fields' => array(
				array(
					'key' => 'field_5ebc8a0bddfde',
					'label' => 'Import',
					'name' => 'font_import',
					'type' => 'text',
					'instructions' => 'Add a URL for a hosted font',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5ebc8a17ddfdf',
			'label' => 'Font Faces',
			'name' => 'font_faces',
			'type' => 'repeater',
			'instructions' => 'Define Font Faces to use custom fonts',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Font Face',
			'sub_fields' => array(
				array(
					'key' => 'field_5ebc8a1eddfe0',
					'label' => 'Font Face',
					'name' => 'font_face',
					'type' => 'textarea',
					'instructions' => 'Define a @font-face',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '@font-face {
  font-family: "";
  src: url(/wp-content/themes/diocesan/fonts/…);
}',
					'placeholder' => '@font-face {
  font-family: "Font Name";
  src: url(/wp-content/themes/diocesan/fonts/Font-Name.ttf);
}',
					'maxlength' => '',
					'rows' => '4',
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_5ebc5b89eb978',
			'label' => 'Font Heading',
			'name' => 'font_heading',
			'type' => 'text',
			'instructions' => 'Default font: serif',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33334',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ebc5ba5eb979',
			'label' => 'Font Script',
			'name' => 'font_script',
			'type' => 'text',
			'instructions' => 'Default font: cursive',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ebc5bafeb97a',
			'label' => 'Font Main',
			'name' => 'font_main',
			'type' => 'text',
			'instructions' => 'Default font: sans-serif',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dd2a5948b445',
			'label' => 'Headings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5dd2a5f592fae',
			'label' => 'Heading 1',
			'name' => 'heading_1',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33334',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2c42c0bad6',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2c4830bad7',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2c42c0bad6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'tertiary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2a62e92faf',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2c42c0bad6',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2a64692fb0',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 30,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b90e0357f',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '400',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bf1945132',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_heading',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ac83fe95f',
			'label' => 'Heading 2',
			'name' => 'heading_2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2d0990bad8',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2d1af0badd',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0990bad8',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'tertiary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ac83fe960',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0990bad8',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ac83fe961',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 28,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b97903580',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '700',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bfa245133',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_main',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ac87fe962',
			'label' => 'Heading 3',
			'name' => 'heading_3',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2d0db0bad9',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2d1bd0bade',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0db0bad9',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'tertiary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ac87fe963',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0db0bad9',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ac87fe964',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 26,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b98903581',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '400',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bfae45134',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_heading',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ac89fe965',
			'label' => 'Heading 4',
			'name' => 'heading_4',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33334',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2d0ef0bada',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2d1cb0badf',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0ef0bada',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'primary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ac89fe966',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d0ef0bada',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ac89fe967',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 24,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b99903582',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '400',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bfb945135',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_heading',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ac8bfe968',
			'label' => 'Heading 5',
			'name' => 'heading_5',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2d1020badb',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2d1e10bae0',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d1020badb',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'primary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ac8bfe969',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d1020badb',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ac8bfe96a',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 20,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b9b703583',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '700',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bfc445136',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_heading',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ac8dfe96b',
			'label' => 'Heading 6',
			'name' => 'heading_6',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33333',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2d1340badc',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2d1fc0bae1',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d1340badc',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'tertiary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ac8dfe96c',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2d1340badc',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ac8dfe96d',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 18,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
				array(
					'key' => 'field_5dd2b9c403584',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => '700',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2bfd045137',
					'label' => 'Font Family',
					'name' => 'font_family',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'font_heading' => 'Heading',
						'font_script' => 'Script',
						'font_main' => 'Main',
					),
					'default_value' => 'font_main',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd2ed6ff663d',
			'label' => 'Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5dd2ed8af663e',
			'label' => 'Paragraph',
			'name' => 'paragraph',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5f984539f0bd3',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5f9846bdf0bd4',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f984539f0bd3',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'tertiary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f98481af0bd5',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f984539f0bd3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#454545',
				),
				array(
					'key' => 'field_5dd2ed8af6642',
					'label' => 'Font Size',
					'name' => 'font_size',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 18,
					'min' => 10,
					'max' => 100,
					'step' => '',
					'prepend' => '',
					'append' => 'px',
				),
			),
		),
		array(
			'key' => 'field_5dd2ef47a8567',
			'label' => 'Links',
			'name' => 'anchor_link',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd2ef47a8568',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5dd2ef47a8569',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2ef47a8568',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => 'secondary_color',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2ef47a856a',
					'label' => 'Color',
					'name' => 'heading_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5dd2ef47a8568',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#3D3D3D',
				),
				array(
					'key' => 'field_5dd2ef47a856c',
					'label' => 'Font Weight',
					'name' => 'font_weight',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'400'  => 'Regular',
						'400i' => 'Regular Italic',
						'600'  => 'Semi-Bold',
						'600i' => 'Semi-Bold Italic',
						'700'  => 'Bold',
						'700i' => 'Bold Italic',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd2efb6a856e',
					'label' => 'Font Style',
					'name' => 'font_style',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'italic' => 'Italic',
						'underline' => 'Underline',
					),
					'allow_custom' => 0,
					'default_value' => array(),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5dd2f1cc2a63f',
					'label' => 'Hover Styles',
					'name' => 'hover_styles',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5dd2f1f32a641',
							'label' => 'Color Selector',
							'name' => 'color_selector',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => 'Use main site colors?',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5dd2f1f32a642',
							'label' => 'Site Colors',
							'name' => 'site_colors',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd2f1f32a641',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'primary_color' => 'Primary',
								'secondary_color' => 'Secondary',
								'tertiary_color' => 'Tertiary',
								'quaternary_color' => 'Quaternary',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5dd2f1f32a643',
							'label' => 'Color',
							'name' => 'heading_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd2f1f32a641',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#3D3D3D',
						),
						array(
							'key' => 'field_5dd2f21d2a647',
							'label' => 'Font Style',
							'name' => 'font_style',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'italic' => 'Italic',
								'underline' => 'Underline',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5dd2f6e0028ed',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6022da5112605',
			'label' => 'Single Post Title',
			'name' => 'post_title',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_6022da7b12606',
					'label' => 'Custom Text?',
					'name' => 'is_custom_text',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Custom',
					'ui_off_text' => 'Category',
				),
				array(
					'key' => 'field_6022dad412607',
					'label' => 'Custom Text',
					'name' => 'custom_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6022da7b12606',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Details',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5ebaccd38ed46',
			'label' => 'Page Header Overlay',
			'name' => 'page_header_overlay',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ebac77414641',
					'label' => 'Color Selector',
					'name' => 'color_selector',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => 'Use main site colors?',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5ebac8eb14642',
					'label' => 'Site Colors',
					'name' => 'site_colors',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ebac77414641',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'primary_color' => 'Primary',
						'secondary_color' => 'Secondary',
						'tertiary_color' => 'Tertiary',
						'quaternary_color' => 'Quaternary',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ebac96714643',
					'label' => 'Color',
					'name' => 'hero_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ebac77414641',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array(
					'key' => 'field_5ebad5ddb19be',
					'label' => 'Opacity',
					'name' => 'opacity',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'0' => 'No Overlay',
						'0.125' => 'Extra Light Overlay',
						'0.25' => 'Light Overlay',
						'0.5' => 'Medium Overlay',
						'0.75' => 'Heavy Overlay',
					),
					'default_value' => array(
						0 => '0.25',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5dd310e60a2a4',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eb1cb235547e',
			'label' => 'GTranslate',
			'name' => 'gtranslate',
			'type' => 'true_false',
			'instructions' => 'Check this box if GTranslate is configured, and you wish to include it in the footer.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5dd4490ef7f9c',
			'label' => 'Tweaks',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5dd44942f7f9d',
			'label' => 'Tweaks',
			'name' => 'tweaks',
			'type' => 'textarea',
			'instructions' => 'Add custom CSS to be applied to the site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ee7cd42d21dc',
			'label' => 'Other',
			'name' => '',
			'type' => 'tab',
			'instructions' => 'This is currently just a placeholder.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5fa1cca283cd7',
			'label' => 'Has Mega Menu?',
			'name' => 'has_mega_menu',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5fb56e299f5fd',
			'label' => 'Background',
			'name' => 'background',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fa1cca283cd7',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'primary' => 'Primary',
				'secondary' => 'Secondary',
				'tertiary' => 'Tertiary',
				'quaternary' => 'Quaternary',
				'white' => 'White',
			),
			'default_value' => 'white',
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fbbe58bb9735',
			'label' => 'Color',
			'name' => 'color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fa1cca283cd7',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'primary' => 'Primary',
				'secondary' => 'Secondary',
				'tertiary' => 'Tertiary',
				'quaternary' => 'Quaternary',
				'white' => 'White',
			),
			'default_value' => 'primary',
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fbbec1ca55c6',
			'label' => 'Border Color',
			'name' => 'border_color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fa1cca283cd7',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'primary' => 'Primary',
				'secondary' => 'Secondary',
				'tertiary' => 'Tertiary',
				'quaternary' => 'Quaternary',
				'white' => 'White',
			),
			'default_value' => 'quaternary',
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fbbe5afb9737',
			'label' => 'Hover Color',
			'name' => 'hover_color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fa1cca283cd7',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'primary' => 'Primary',
				'secondary' => 'Secondary',
				'tertiary' => 'Tertiary',
				'quaternary' => 'Quaternary',
				'white' => 'White',
			),
			'default_value' => 'secondary',
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fbc80882e691',
			'label' => 'Custom Excerpts?',
			'name' => 'has_custom_excerpts',
			'type' => 'true_false',
			'instructions' => 'This is NOT recommended without additional training.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'template-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
