<?php acf_add_local_field_group(array(
	'key' => 'group_5db8a01f3bacb',
	'title' => 'Theme Settings',
	'fields' => array(
		array(
			'key' => 'field_5db9d42fe54e6',
			'label' => 'Church Info',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5db8a028c8c3d',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'link',
			'instructions' => 'Put the URL from Google Maps in "URL" and how the Address should be displayed in "Link Text."',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5dc9bed40c3f5',
			'label' => 'Iframe',
			'name' => 'iframe',
			'type' => 'text',
			'instructions' => 'Paste contents of src from the iframe in "Embed a Map" on Google Maps.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5db8a9f09f895',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '(###) ###-####',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dc9d4fb4b88f',
			'label' => 'Fax',
			'name' => 'fax',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5db8a9f79f896',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5db9df6db7b81',
			'label' => 'Mass Times & Schedule',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5db9dfeeb7b82',
			'label' => 'Schedule',
			'name' => 'schedule',
			'type' => 'repeater',
			'instructions' => 'Up to 3 Sections can be displayed on the Homepage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Section',
			'sub_fields' => array(
				array(
					'key' => 'field_5e7b93845228b',
					'label' => 'Section Title',
					'name' => 'section_title',
					'type' => 'text',
					'instructions' => 'Section Titles will only be shown on the Mass Times page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '85',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e7b9582b8df2',
					'label' => 'Show Section',
					'name' => 'show',
					'type' => 'true_false',
					'instructions' => 'Show on Homepage?<br />*Max: 3',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5e7b93ec5228c',
					'label' => 'Times',
					'name' => 'times',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Time',
					'sub_fields' => array(
						array(
							'key' => 'field_5db9e02fb7b83',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => 'Do not include any colons or other punctuation.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5db9e038b7b84',
							'label' => 'Detail',
							'name' => 'detail',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5e7a41fe4346d',
							'label' => 'Show Time',
							'name' => 'show',
							'type' => 'true_false',
							'instructions' => 'Show on Homepage?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5e7a23db26383',
			'label' => 'Schedule Link',
			'name' => 'schedule_link',
			'type' => 'link',
			'instructions' => '"Link Text" will be shown in the link above the Mass Times on the homepage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5dc9d5e0fc1a3',
			'label' => 'Office Hours',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5dc9d5eafc1a4',
			'label' => 'Office Hours',
			'name' => 'office_hours',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5dc9d617fc1a5',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => 'Do not include any colons or other punctuation.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5dc9d620fc1a6',
					'label' => 'Detail',
					'name' => 'detail',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_601963a0b984a',
			'label' => 'Staff',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60241a0157ab7',
			'label' => 'Image Style',
			'name' => 'is_staff_complex',
			'type' => 'true_false',
			'instructions' => 'What style should be used for ministry contacts?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Complex',
			'ui_off_text' => 'Simple',
		),
		array(
			'key' => 'field_601962b11a86f',
			'label' => 'Image Alignment',
			'name' => 'staff_image_alignment',
			'type' => 'select',
			'instructions' => 'Select the vertical alignment for staff images.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'center' => 'Center',
				'bottom' => 'Bottom',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_603d5b29890c8',
			'label' => 'View All Button',
			'name' => 'view_all_staff',
			'type' => 'link',
			'instructions' => 'If using a custom Staff Archive, add the link here. Otherwise, please leave this blank.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5e989770758c0',
			'label' => 'Social Media',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e98a518ffaa8',
			'label' => 'Social Media',
			'name' => 'social_media',
			'type' => 'repeater',
			'instructions' => 'Set values for social media accounts. *Max: 8',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 8,
			'layout' => 'block',
			'button_label' => 'Add Link',
			'sub_fields' => array(
				array(
					'key' => 'field_5e98a518ffaa9',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'font-awesome',
					'instructions' => 'This icon will be shown in the social media section in the footer.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
						2 => 'fab',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5e98a518ffaaa',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => 'This is where this link will take someone who clicks it.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5ecd34d13399d',
			'label' => 'myParish',
			'name' => 'myParish_group',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e98a891caa7e',
					'label' => 'myParish?',
					'name' => 'has_myParish',
					'type' => 'true_false',
					'instructions' => 'Uncheck if you do not have the myParish app.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5e98a944caa7f',
					'label' => 'myParish (Optional)',
					'name' => 'myParish',
					'type' => 'link',
					'instructions' => 'Set a custom link for your myParish app. If a link is not set, users will be linked to myParish\'s website.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5e98a891caa7e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5ecd345f257ad',
			'label' => 'Evangelus',
			'name' => 'evangelus_group',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ec53d0cd7983',
					'label' => 'Evangelus?',
					'name' => 'has_evangelus',
					'type' => 'true_false',
					'instructions' => 'Uncheck if you do not have Evangelus.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5ec53d89d7984',
					'label' => 'Evangelus (Optional)',
					'name' => 'evangelus',
					'type' => 'link',
					'instructions' => 'Set a custom link for Evangelus. If a link is not set, users will be linked to Evangelus\'s website.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ec53d0cd7983',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 96,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set values to be used throughout the site, including the church\'s information & schedule.',
));
