<?php // CPT: Homily
register_post_type('homily',
  array(
    'label'   => __( 'Homily' ),
    'labels'  => array(
      'name'                  => _x( 'Homilies', 'Post type general name' ),
      'singular_name'         => _x( 'Homily', 'Post type singular name' ),
      'menu_name'             => _x( 'Homilies', 'Admin Menu text' ),
      'name_admin_bar'        => _x( 'Homily', 'Add New on Toolbar' ),
      'add_new'               => __( 'Add Homily' ),
      'add_new_item'          => __( 'Add New' ),
      'new_item'              => __( 'New Homily' ),
      'edit_item'             => __( 'Edit Homily' ),
      'view_item'             => __( 'View Homily' ),
      'all_items'             => __( 'All Homilies' ),
      'search_items'          => __( 'Search Homilies' ),
      'parent_item_colon'     => __( 'Parent Homilies:' ),
      'not_found'             => __( 'No Homilies found.' ),
      'not_found_in_trash'    => __( 'No Homilies found in Trash.' ),
      'featured_image'        => _x( 'Homily Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3' ),
      'set_featured_image'    => _x( 'Set Homily Image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3' ),
      'remove_featured_image' => _x( 'Remove Homily Image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3' ),
      'use_featured_image'    => _x( 'Use as Homily Image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3' ),
      'archives'              => _x( 'Homilies', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4' ),
      'insert_into_item'      => _x( 'Insert into Homily', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4' ),
      'uploaded_to_this_item' => _x( 'Uploaded to this Homily', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4' ),
      'filter_items_list'     => _x( 'Filter Homilies List', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4' ),
      'items_list_navigation' => _x( 'Homilies List Navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4' ),
      'items_list'            => _x( 'Homilies List', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4' ),
    ),
    'public'              => true,
    'publicly_queryable'  => true,
    'exclude_from_search' => false,
    'menu_icon'           => 'dashicons-book-alt',
    'show_ui'             => true,
    'show_in_menu'        => true,
    'show_in_rest'        => true,
    'query_var'           => true,
    'capability_type'     => 'post',
    'has_archive'         => true,
    'hierarchical'        => true,
    'menu_position'       => null,
    'supports'            => array(
      'author',
      'editor',
      'page-attributes',
      'thumbnail',
      'title',
    ),
    'rewrite'  => array( 'slug' => 'ministries' ),
    'has_archive'         => 'ministries',
  )
);

// Register Taxonomy: Liturgical Season
register_taxonomy( 'liturgical-season', array( 'homily' ), array(
  'label'   => __( 'Liturgical Season' ),
  'labels'  => array(
    'name'              => _x( 'Liturgical Season', 'taxonomy general name' ),
    'singular_name'     => _x( 'Liturgical Season', 'taxonomy singular name' ),
    'search_items'      => __( 'Search Liturgical Seasons' ),
    'all_items'         => __( 'All Liturgical Seasons' ),
    'parent_item'       => __( 'Parent Liturgical Season' ),
    'parent_item_colon' => __( 'Parent Liturgical Season:' ),
    'edit_item'         => __( 'Edit Liturgical Season' ),
    'update_item'       => __( 'Update Liturgical Season' ),
    'add_new_item'      => __( 'Add New Liturgical Season' ),
    'new_item_name'     => __( 'New Liturgical Season Name' ),
    'menu_name'         => __( 'Liturgical Seasons' ),
  ),
  'hierarchical'      => true,
  'show_ui'           => true,
  'show_in_rest'      => true,
  'show_admin_column' => true,
  'query_var'         => true,
) );
