<?php acf_add_local_field_group(array(
  'key' => 'group_5cb737b1040de',
  'title' => 'Image Banner',
  'fields' => array(
    array(
      'key' => 'field_5cb7396dc57ad',
      'label' => 'Background',
      'name' => 'image_banner_background',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'large',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'default_value' => '',
    ),
    array(
      'key' => 'field_5cb739a6c57ae',
      'label' => 'Title',
      'name' => 'image_banner_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array(
      'key' => 'field_5cb739bfc57af',
      'label' => 'Content',
      'name' => 'image_banner_content',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => '',
    ),
    array(
      'key' => 'field_5cb739c7c57b0',
      'label' => 'Buttons',
      'name' => 'image_banner_buttons',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 2,
      'layout' => 'block',
      'button_label' => 'Add Button',
      'sub_fields' => array(
        array(
          'key' => 'field_5cb73a73c57b1',
          'label' => 'Button',
          'name' => 'button',
          'type' => 'link',
          'instructions' => '"Link Text" will be shown in the button.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
        ),
      ),
    ),
    array(
      'key' => 'field_5eb411b63e439',
      'label' => 'Bottom Padding',
      'name' => 'bottom_padding',
      'type' => 'true_false',
      'instructions' => 'Keep this box checked if you want white space below this block.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/image-banner',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));
